### ISSUE TITLE
Use terminal.styledEcho?

### ISSUE THREAD

**Issue by kaushalmodi** [icyphox/fab#1]
Hello,

I see that you are using the ANSI escape codes at low level.

Have you looked at [`terminal.styledEcho`][1]? May be having your procs wrappers around styledEcho adds Windows compatibility?

> On UNIX, the implementation simply uses ANSI escape sequences and does not depend on any other module, on Windows it uses the Windows API. 

[1]: https://nim-lang.org/docs/terminal.html#17

**Comment by icyphox** [comment]
Hey, 
I'm aware of `terminal.styledEcho`, but I couldn't seem to `echo` multiple colors in a single line.  
Perhaps submit a PR if you can get it to work?

**Comment by kaushalmodi** [comment]
See https://github.com/kaushalmodi/fab/blob/use-styled-echo/README.md.

**Comment by kaushalmodi** [comment]
I agree that the procs don't get composable as in your approach, but it's still possible, and IMO the code is more readable.

In summary, you don't have to merge this. But this was a fun exercise :)

**Comment by icyphox** [comment]
I saw your repo, and hey, it looks good to me. Feel free to submit a PR :')

I'm going to reopen this, if someone has a better approach.
