### ISSUE TITLE
Update docs in the README

### ISSUE THREAD

**Issue by s0kil** [icyphox/fab#8]
A great feature would be to be able to bold a color.
`bold(blue("Hey! I'm BOLD and blue"))`

Something similar to this: https://github.com/fatih/color
```go
red := color.New(color.FgRed)

boldRed := red.Add(color.Bold)
```

**Comment by icyphox** [comment]
It's already been implemented actually, take a look at [this](https://github.com/icyphox/fab/blob/master/src/fab.nim#L98). My lazy ass just hasn't updated the README with the new stuff yet.
I guess I'll edit the issue title to read 'Update documentation in the README', instead.

**Comment by s0kil** [comment]
@icyphox 
Is this the cleanest way to use it?
```nim
import ../src/fab
import terminal

blue("this is bold blue", sty = {styleBright})
```

**Comment by icyphox** [comment]
At the moment, yes.

**Comment by icyphox** [comment]
Thanks for your contribution! Closing this now.
